language: python
python:
  - "2.7"

# command to install dependencies
install: "pip install -r requirements.txt"

# command to create db
before_script: "python db_create_db.py"

# command to run tests
script:
  - python manage.py test
