"""empty message

Revision ID: 1e106584c9b7
Revises: 29034780b636
Create Date: 2015-07-10 07:25:30.388994

"""

# revision identifiers, used by Alembic.
revision = '1e106584c9b7'
down_revision = '29034780b636'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('features', sa.Column('slug', sa.String(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('features', 'slug')
    ### end Alembic commands ###
