"""empty message

Revision ID: 240043bbba94
Revises: 1e106584c9b7
Create Date: 2015-09-05 23:48:31.955832

"""

# revision identifiers, used by Alembic.
revision = '240043bbba94'
down_revision = '1e106584c9b7'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('photos', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('photos', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    ### end Alembic commands ###
