"""empty message

Revision ID: 36509e4e45a0
Revises: 80b48a05077
Create Date: 2015-07-04 15:18:53.403872

"""

# revision identifiers, used by Alembic.
revision = '36509e4e45a0'
down_revision = '80b48a05077'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(), nullable=False))
    op.drop_constraint(u'users_name_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(u'users_name_key', 'users', ['name'])
    op.drop_column('users', 'username')
    ### end Alembic commands ###
