"""empty message

Revision ID: 80b48a05077
Revises: 2342bba91933
Create Date: 2015-07-04 10:07:41.910291

"""

# revision identifiers, used by Alembic.
revision = '80b48a05077'
down_revision = '2342bba91933'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['name'])
    op.drop_column('users', 'email')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    ### end Alembic commands ###
